import React from 'react'
import ChatGPT from './assets/ChatGPt.jpeg'
import Claude from './assets/Claude.jpeg'
import Gemini from './assets/Gemini.jpeg'
import Deepseek from './assets/Deepseek.jpeg'
import Perplexity from './assets/Perplexity.jpeg'
import Grok from './assets/Grok.jpeg'
import Meta from './assets/Meta.jpeg'

export default function App() {
  // Descriptions used below are all generated by AI
  const myList1 = [{
    title: "ChatGPT",
    image: ChatGPT,
    desc: "ChatGPT is an advanced artificial intelligence chatbot developed by OpenAI. It is powered by the GPT (Generative Pre-trained Transformer) family of models, which are designed to understand and generate human-like language. It is a virtual assistant that can understand and respond to questions, hold conversations, help with writing, explain complex topics, assist with coding, translate languages, and much more. It works like a smart chatbot you can talk to about almost anything."
  },
  {
    title: "Gemini",
    image: Gemini,
    desc: "Gemini is Google DeepMind’s cutting-edge family of large language models, launched in December 2023 as successors to LaMDA and PaLM. It stands out for its native multimodality, meaning it can simultaneously process and generate text, images, audio, video, and code—all within a shared context window "
  },
  {
    title: "DeepSeek",
    image: Deepseek,
    desc: "DeepSeek is a Chinese artificial intelligence company and model family known for building powerful, open-source AI systems that rival leading models like OpenAI's ChatGPT and Google's Gemini—but at a much lower cost. Itdevelops large language and code models that can read, understand, and generate human-like text, solve math problems, write code, and reason across multiple topics. It’s part of a new wave of highly capable, efficient, and open AI models."
  },
  {
    title: "Claude",
    image: Claude,
    desc: "Claude is a family of advanced conversational AI models developed by Anthropic, a safety-focused startup founded by former OpenAI researchers. Named after Claude Shannon, the “father of information theory,” Claude is designed to be helpful, honest, and harmless, guided by a unique training approach called Constitutional AI "
  },
  {
    title: "Perplexity",
    image: Perplexity,
    desc: "Perplexity AI is a conversational search and answer engine that combines advanced large language models with real-time web searching to deliver direct, up-to-date, and well-cited responses. It  is a next-gen search tool where users ask questions and receive synthesized answers, complete with inline citations, instead of a list of links "
  },
  {
    title: "Grok",
    image: Grok,
    desc: "Grok is a conversational AI chatbot developed by xAI, the artificial intelligence company founded by Elon Musk in 2023. It launched in November 2023 and integrates deeply with the X platform (formerly Twitter), known for its witty, sometimes sarcastic personality and real-time web awareness"
  },
  {
    title: "Meta AI",
    image: Meta,
    desc: "Meta AI refers to the suite of advanced artificial intelligence models, tools, and applications developed by Meta Platforms, Inc. (formerly Facebook), aimed at transforming how people interact with technology through generative AI and conversational agents. Meta AI represents the company’s strategic push into the AI era, leveraging cutting-edge research, massive data, and its enormous social and hardware ecosystem to create intelligent, multimodal systems that can understand, generate, and interact with humans naturally."
  }];

  return (
    <div>
      {myList1.map((item) => {
        return (
          <div key={item.title} className="m-5 p-4 border border-blue-500 shadow-xl shadow-cyan-700 flex">
            <div className="flex flex-col h-full w-[70%]">
              <h1 className="text-2xl font-bold shadow-md shadow-blue-900 p-[10px] m-[10px] w-35 cursor-pointer bg-gradient-to-r from-cyan-300 to-blue-400">{item.title}</h1>
              <p className="font-semibold w-[70%] bg-gradient-to-r from-cyan-100 to-blue-100 p-5 ">{item.desc}</p>
            </div>
            <div className="flex justify-center items-center w-[30%]">
              <img src={item.image} alt="Logo" className="h-[135px] w-[150px] border p-[20px] rounded-xl cursor-pointer" />
            </div>
          </div>
        )
      })}
    </div>
  )
}
